name: golangci-lint
on:
  push:
    branches:
      - main
    paths:
      - '**.go'
    tags-ignore:
      - '**'

  pull_request:
    paths:
      - '**.go'

concurrency:
  group: golangci-lint-sslpd
  cancel-in-progress: true

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60
          args: --timeout=5m
